### ISSUE TITLE
我很希望bilibili和twitter两个部分支持用户自己选择是否一起发送链接 或是分开发送

### ISSUE THREAD

**Issue by logiest617** [Kabuda-czh/koishi-plugin-kbot#27]
我的bot被风控了，如果发送的消息内容同时有图片和文字，就一定会被风控，虽然可以选择图片模式，但是链接依然是文本形式，因此我很希望可以让用户自己选择是否发送链接，或是链接和图片分开发送

**Comment by Kabuda-czh** [comment]
发送图文并不会引起风控, 请检查自己的 bot, 以及是否发送了敏感信息, 分开发送或许会考虑
