### ISSUE TITLE
你好，为什么我在群内发送bilibili没有反应

### ISSUE THREAD

**Issue by lzx123456123** [Kabuda-czh/koishi-plugin-kbot#29]
群管的插件可以正常反馈但是bilibili没有发送
![图片](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/50208717/7c8edcac-250c-43e7-a92a-38ff519c154c)

**Comment by lzx123456123** [comment]
![图片](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/50208717/6be5dca3-f8f1-4fc8-830b-c6c3878445ce)

**Comment by lzx123456123** [comment]
![图片](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/50208717/0c4cea4c-c7fa-4792-80ae-94828f2496d5)
查弹幕和查成分还有更新vup我不知道我的方法哪里出现错误了

**Comment by Kabuda-czh** [comment]
查弹幕的话 可能是 danmuku 网站问题, 其他的话你能提供一下你的日志吗

**Comment by lzx123456123** [comment]
> 查弹幕的话 可能是 danmuku 网站问题, 其他的话你能提供一下你的日志吗

![图片](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/50208717/260ea85b-c2b3-4d13-9607-df4b8005ac72)
是这个吗

**Comment by Kabuda-czh** [comment]
这里的问题的话呢, 你需要在数据文件夹下找到
public 文件夹
然后创建 bilibili 文件夹
然后创建 vup.json 文件

**Comment by lzx123456123** [comment]
> > 查弹幕的话 可能是 danmuku 网站问题, 其他的话你能提供一下你的日志吗
> 
> ![图片](https://user-images.githubusercontent.com/50208717/241361314-260ea85b-c2b3-4d13-9607-df4b8005ac72.png) 是这个吗

而且我添加到频道提示权限不足，我已经用了login插件提权了，在QQ群是正常功用的
![图片](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/50208717/73bd8813-1a58-4a94-9660-27480cca629c)

**Comment by lzx123456123** [comment]
> 这里的问题的话呢, 你需要在数据文件夹下找到 public 文件夹 然后创建 bilibili 文件夹 然后创建 vup.json 文件

你好我添加文件后又出现这个提示
![图片](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/50208717/5adfe1ed-d705-408f-947d-024a74c1a67d)

**Comment by Kabuda-czh** [comment]
那么在 json 文件中 添加 {} 这个东西

**Comment by lzx123456123** [comment]
> 

![图片](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/50208717/b52b5436-3d2f-407d-9be0-1f2f7bdb4002)
![图片](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/50208717/78f075da-f9ce-470c-85c3-28f89e01ba16)

大佬我添加了以后还是提示报错，o(╥﹏╥)o

**Comment by Kabuda-czh** [comment]
fetch 没有诶 我去问问 kd 的 node 版本是什么

**Comment by lzx123456123** [comment]
> 

好哒
