### ISSUE TITLE
无法使用bilibili -v

### ISSUE THREAD

**Issue by yi03** [Kabuda-czh/koishi-plugin-kbot#32]
我已经填写了cookie，目前`bilibili -s`和`bilibili -d`都能正常使用，所以cookie应该填的没问题，但是在使用bilibili -v时会报错`cookie信息未找到, 请使用 --ck 或 --cookie 更新cookie信息`。

**Comment by yi03** [comment]
感觉也有可能是我cookie填错了，我的cookie是这么填的：
使用Cookie-Editor插件将b站的cookie完整的导出，粘贴到public\kbot\bilibili\cookie.json里，保存，重启koishi。

**Comment by Kabuda-czh** [comment]
Cookie-Editor
没有使用过, 所以我不清楚他的格式是否能正确被我解析

**Comment by Kabuda-czh** [comment]
如果还有问题可以说一下
