### ISSUE TITLE
动态轮询提示 Error: undefined

### ISSUE THREAD

**Issue by xixi-furry** [Kabuda-czh/koishi-plugin-kbot#35]
日志直接提示：KBot-bilibili-dynamic 轮询 Error: undefined
已配置cookie，配置是从访问主页时候右键检查里的cookie丢进cookie转json然后丢到public下面的那个。
是cookie配置的问题吗？

**Comment by yi03** [comment]
+1。我也碰到了这个问题。

**Comment by Kabuda-czh** [comment]
我也 `undefined` 这个是 B站 接口的不稳定
得去对接一下了

**Comment by Kabuda-czh** [comment]
暂时解决不了, 如果遇到 undefined, 可以尝试重启一下 bot

**Comment by skinnydruid** [comment]
已经这样好多天了，重启bot也好多次了，没成功消除过
