### ISSUE TITLE
增加功能

### ISSUE THREAD

**Issue by axlmly** [Kabuda-czh/koishi-plugin-kbot#39]
希望能在-l里加入编号，之后再-s的时候可以调用这个编号里添加的人

**Comment by Kabuda-czh** [comment]
你指的是什么功能?

**Comment by axlmly** [comment]
> 你指的是什么功能?

订阅动态的功能的-l不是列出订阅目标吗，但是每次都要输入一大串数字感觉有些繁琐，就算是复制粘贴也够麻烦（手机），所以能否再列出目标的同时在前面也列出对应的数字或字母，只要调用前面的字母与数字就可以代替uid与名字调用
类似：
指令
 bilibili（twitter） -l 
输出
- #1 uid 姓名
指令
bilibili（twitter） -s #1
输出#1内的信息
这样，我想作为订阅的话应该是不会出现三位数，所以这应该是比较方便的调用方式。
以及增加-s的另一种调用，不需要使用指令前缀的那种，通过监听用户消息触发，例如“xx的最新动态”（xx可以是上面三种），可以添加一个可自定义的触发选项。
希望在增加一下-l的列表的信息，例如：uid 姓名 粉丝数量 最后一次动态时间
