### ISSUE TITLE
直播时长算错了

### ISSUE THREAD

**Issue by yi03** [Kabuda-czh/koishi-plugin-kbot#45]
发送`bilibili -d`命令时，发现所有主播的直播时长都是46万多小时。
应该是因为这一行少加了个括号。三元运算符的优先级比减号低。
https://github.com/Kabuda-czh/koishi-plugin-kbot/blob/c488ac1c5795a0a7a0209b8ea02f7be5e6a1a388/plugins/kbot/src/plugins/bilibili/dynamic/composition/render.tsx#L310

**Comment by Kabuda-czh** [comment]
已修复, 中午会发版
