### ISSUE TITLE
推特接口404

### ISSUE THREAD

**Issue by MsSusai** [Kabuda-czh/koishi-plugin-kbot#56]
推特接口好像炸了，添加和批量添加都是404，添加不了用户  

<img width="532" alt="image" src="https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/66015828/656be024-0973-4e62-beb6-94517e2af50c">

![image](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/66015828/85870a64-b7bb-45f5-b04f-bc4c6ec4b174)

**Comment by Kabuda-czh** [comment]
已经修了 38f585600fe7957f377e7f306f2f3275ddb20536 但我没发版 应该在明天发版 今天有些其他的事情 抱歉

**Comment by Kabuda-czh** [comment]
下午修好了的 应该是推特把游客入口关闭了
今后会让用户自己添加token使用了
