### ISSUE TITLE
关于B站和推特动态订阅配置cookie的问题

### ISSUE THREAD

**Issue by AkatsukiZhang** [Kabuda-czh/koishi-plugin-kbot#62]
配置cookie需要的格式和字段，我在说明文档里翻了几遍都没看到，不知道如何配置。
有比较详细的说明吗?

**Comment by Kabuda-czh** [comment]
通过一些获取B站Cookie的软件
或者通过网页版B站 -> F12 打开 DevTools -> 找到 Network 项 -> 找到其中的请求链接 -> 将其中的 Cookie 全部复制给机器人即可(下面是图例)
![image](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/62021214/a867db8e-4957-4a13-8564-48305dee99b4)
![image](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/62021214/40f7697d-e7ff-42ff-91ea-baafab37ed72)
![image](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/62021214/cb035030-fce5-4496-a5a6-0e53eb622586)
![image](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/62021214/8f258bdd-ca32-4c6b-8570-defe954010ad)
