### ISSUE TITLE
bilibili这个是怎么回事

### ISSUE THREAD

**Issue by Annnnh1010** [Kabuda-czh/koishi-plugin-kbot#69]
![VeryCapture_20230722135659](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/76246787/b158b8aa-4ef3-4e93-849d-0d08496caf33)

**Comment by Kabuda-czh** [comment]
就是 cookie 过期了或者你更新后对应位置文件里面没有 cookie

**Comment by Annnnh1010** [comment]
刚安装  这个cookie怎么配置？

KBD ***@***.***> 于2023年7月22日周六 14:57写道：

**Comment by Kabuda-czh** [comment]
自行在 web 端获取到你登陆账户的 cookie
然后通过 bilibili --ck cookie 发送给机器人啊
如果不知道怎么获取请自行查看这个 issue #62
