### ISSUE TITLE
我更新了推特的cookie，为何还是无法查询动态

### ISSUE THREAD

**Issue by OneTrueSum95** [Kabuda-czh/koishi-plugin-kbot#70]
![1232](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/116902021/6805c19f-9b15-47bd-8b62-4ac5864ddb05)

**Comment by Kabuda-czh** [comment]
最好提供一下日志哦

**Comment by OneTrueSum95** [comment]
> 

日志报错[E] KBot-twitter-dynamic error getTwitterRestId: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

cookie里该有的字段都有呀

**Comment by Kabuda-czh** [comment]
那能否方便你发送 kbot-data 下 twitter 文件夹里面的 cookie.json 吗

**Comment by OneTrueSum95** [comment]
> 那能否方便你发送 kbot-data 下 twitter 文件夹里面的 cookie.json 吗

{"cookieString":"lang=zh-cn;gt=1683001755305652224;_gid=GA1.2.960940059.1690093863;kdt=GnLFZ3bulaznGYzlcdcODLghvcEmTMsCdySrLxUl;at_check=true;mbox=session#ea02cb6b61104fc58130e654006f2f5d#1690103016|PC#ea02cb6b61104fc58130e654006f2f5d.34_0#1753345956;_ga_BYKEBDM7DS=GS1.1.1690101042.1.1.1690101166.0.0.0;_ga=GA1.2.1255487022.1690093863;ads_prefs=\"HBIRAAA;auth_multi=\"1590444876881047552:303b3713268faabd7e973c0f3fd1c98b98a8ec9d\";auth_token=9b0427de6f832a30e5dc6b1d1283361d6793396c;guest_id=v1%3A169010132103567923;ct0=3b76d4eecd3a3557d7023ba067e6fba86770334bd6d345724ad33234e8440c51cd5d43a6c93a162b4f2ea5aebddd5ec8046d5a83cd0c6001450f0bc463c4e391f07fb6cfa9def24416c629ba01253471;twid=u%3D962536655226683392;guest_id_marketing=v1%3A169010132103567923;guest_id_ads=v1%3A169010132103567923;personalization_id=\"v1_bwOdULXwvrqhQzqaJY8h1g","authCookie":{"ct0":"3b76d4eecd3a3557d7023ba067e6fba86770334bd6d345724ad33234e8440c51cd5d43a6c93a162b4f2ea5aebddd5ec8046d5a83cd0c6001450f0bc463c4e391f07fb6cfa9def24416c629ba01253471","auth_token":"9b0427de6f832a30e5dc6b1d1283361d6793396c"}}

这里面有什么问题吗

**Comment by OneTrueSum95** [comment]
![QQ截图20230723212946](https://github.com/Kabuda-czh/koishi-plugin-kbot/assets/116902021/44c48d47-8f35-4afa-857d-8f820fbeb60e)
还有一点是用twitter -ck +cookie和twitter --cookie +cookie，后面的cookie一样，但bot返回的结果不同

**Comment by Kabuda-czh** [comment]
今天我使用你的 cookie 并没有任何的问题
目前并不清楚为什么会报错

**Comment by OneTrueSum95** [comment]
重启数次后换了一个号的cookie，问题自己解决了！？

**Comment by Kabuda-czh** [comment]
那么只能判断为你一开始的 cookie 可能有问题
