### ISSUE TITLE
用chronocat登录的bot，发现获取b站动态功能用不了了，其他功能正常

### ISSUE THREAD

**Issue by OneTrueSum95** [Kabuda-czh/koishi-plugin-kbot#71]
后台也没有报错

**Comment by Kabuda-czh** [comment]
用什么功能获取的?
建议截图所有流程 不然我并不清楚你的问题点

**Comment by skinnydruid** [comment]
我也发生同样的问题了，chronocat用-s查看动态无反应，后台无任何信息，-a -v -d都可以正常发送，然后订阅了主播动态后，主播发动态了，也同样无反应后台无信息，沙盒里是正常的，应该是chronocat的问题，目前是0.30版本的chronocat

**Comment by OneTrueSum95** [comment]
是适配器的问题，更新后问题解决
